# Servidor
server.port=8081

# db PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=${JWT_SECRET}
app.jwt.access-expiration-ms=${JWT_EXPIRATION}
app.jwt.refresh-expiration-ms=604800000

# URL del Frontend (para enlaces de email)
app.frontend.url=${APP_FRONTEND_URL:http://localhost:3000}

# Cifrado de Wallets AES-256-GCM
wallet.encryption.password=${WALLET_ENCRYPTION_PASSWORD}
wallet.encryption.salt=${WALLET_ENCRYPTION_SALT}

# Configuración de Gemini Parser
app.gemini.enabled=true
app.gemini.api-key=${GEMINI_KEY}
app.gemini.model=gemini-2.5-flash
app.gemini.base-url=https://generativelanguage.googleapis.com

# URL del agent-service
app.agent-service.url=http://localhost:3001

# Hyperliquid API Mainnet URL
hyperliquid.base-url=https://api.hyperliquid.xyz
hyperliquid.testnet=false

# API Key del Agente n8n
app.agent.api-key=${AGENT_API_KEY}

# Spring Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_EMAIL:demo@gmail.com}
spring.mail.password=${SMTP_PASSWORD:demopass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Habilitar scheduler pool size
spring.task.scheduling.pool.size=2
